services:

  modestio-app:
    #image: modestio
    build: .
    networks:
      - modestio-network
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_HOST: db
    depends_on:
      - db

  db:
    image: postgres:latest
    networks:
      - modestio-network
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mypassword

networks:
  modestio-network:
