services:

  modestio-app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    env_file:
      - env_variables.txt
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - env_variables.txt
