# Generated by Django 4.1.5 on 2023-01-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cats", "0003_photo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Photo",
        ),
        migrations.AddField(
            model_name="cat",
            name="photo",
            field=models.ImageField(null=True, upload_to="photo/"),
        ),
    ]
